/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package robotpathcreator;

import javax.swing.*;

public class App {
    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ignored) {}
        RobotPathCreator creator = new RobotPathCreator();
        creator.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        creator.setSize(800, 500);
        creator.setVisible(true);
    }
}
